// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"time"
)

type Article struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Slug      string
	Filename  string
}
